### ISSUE TITLE
Error--UnboundLocalError

### ISSUE THREAD

**Issue by henry-tujia** [gzycode39/docker-vapoursynth-yuuno#5]
- 视频信息如下：
```
**M2TS, 1 video track, 2 audio tracks, 1 subtitle track, 0:25:06, 24p /1.001
1: Chapters, 6 chapters
2: h264/AVC, 1080p24 /1.001 (16:9)
3: DTS Master Audio, English, 5.1 channels, 16 bits, 48kHz
   (core: DTS, 5.1 channels, 1509kbps, 48kHz)
4: DTS, French, 2.0 channels, 768kbps, 48kHz
5: Subtitle (PGS), Chinese
请输入你想添加的音轨编号 （输入 q 以停止添加音频）: 3
请输入音轨语言（默认为en）:
请输入你想添加的音轨编号 （输入 q 以停止添加音频）: q
请输入你想添加的字幕编号（输入 q 以停止添加字幕）: 5
请输入字幕语言（默认为zh）:
请输入字幕名（默认为zh）:
设置为默认字幕轨道吗？(Y/n) (默认为n）: Y
请输入你想添加的字幕编号（输入 q 以停止添加字幕）: q
您选择的轨道如下：
Video track: 2
Audio track:
3 (en) (eac3to => ac3)
Subtitle track:
5 (zh) (zh) default**
```

- 信息确认后，出现以下错误：
```
Traceback (most recent call last):
  File "vstest.py", line 199, in <module>
    last, awsmf_name = copyscript(script, folder + '.scripts/extract.vpy')
  File "vstest.py", line 156, in copyscript
    return last, awsmf_name
UnboundLocalError: local variable 'last' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/bin/frds", line 591, in <module>
    main()
  File "/usr/local/bin/frds", line 544, in main
    crf_dict = generate_vpy(conf)
  File "/usr/local/bin/frds", line 508, in generate_vpy
    crf_dict[k] = generate_vpy_helper(k, content, v)
  File "/usr/local/bin/frds", line 493, in generate_vpy_helper
    return detect_crf(name, codec, target)
  File "/usr/local/bin/frds", line 482, in detect_crf
    return test_crf(name, codec, crf_begin, crf_begin+crf_range, target, 1)
  File "/usr/local/bin/frds", line 442, in test_crf
    with open("{}.log".format(name)) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'x265.log'
```

**Comment by henry-tujia** [comment]
怀疑 执行`last, awsmf_name = copyscript(script, folder + '.scripts/extract.vpy')`出现错误

**Comment by henry-tujia** [comment]
初始化 last变量后，可以正确运行，但是报出

```
Script evaluation failed:
Python exception: invalid syntax (extract.vpy, line 33)

Traceback (most recent call last):
  File "src/cython/vapoursynth.pyx", line 2241, in vapoursynth.vpy_evaluateScript
  File "/encode/out-encode/.scripts/extract.vpy", line 33
    ext = awsf.SelectRangeEvery(clip=, every=3000, length=45, offset=10000)
                                     ^
SyntaxError: invalid syntax

(1/6) Processing encode with --crf 17

Traceback (most recent call last):
  File "vstest.py", line 332, in <module>
    encode(test + ' ' + ' '.join(codec_opts_passed) + ' ' + vbv_opts + ' ' + info)
TypeError: can only concatenate str (not "_wrap_close") to str
```

**Comment by henry-tujia** [comment]
报错原因为  `encode.ipynb` 中缺少  `src.set_output()`,添加后报出以下：
```
Script evaluation failed:
Python exception: Index: Can't open '/encode/After.the.Storm.2016.BluRay.Remux.1080p.AVC.TrueHD.5.1-HiFi.mkv'

Traceback (most recent call last):
  File "src/cython/vapoursynth.pyx", line 2244, in vapoursynth.vpy_evaluateScript
  File "src/cython/vapoursynth.pyx", line 2245, in vapoursynth.vpy_evaluateScript
  File "/encode/out-encode/.scripts/extract.vpy", line 12, in <module>
    src = core.ffms2.Source(source=r'/encode/After.the.Storm.2016.BluRay.Remux.1080p.AVC.TrueHD.5.1-HiFi.mkv')
  File "src/cython/vapoursynth.pyx", line 2069, in vapoursynth.Function.__call__
vapoursynth.Error: Index: Can't open '/encode/After.the.Storm.2016.BluRay.Remux.1080p.AVC.TrueHD.5.1-HiFi.mkv'
```

**Comment by so-y** [comment]
这是第一次运行该脚本吗，之前是否 demux 失败过
建议完全删除相关文件和目录后再次重试
